name: Publish package

on:
  push:
    tags:
      - "v*"

env:
  cache-name: postgres-migrations

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm ci
      - run: docker pull postgres:13.2
      - env:
          NPM_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # NPM_GITHUB_TOKEN should have access to: write-package
          echo "//npm.pkg.github.com/:_authToken=$NPM_GITHUB_TOKEN" >> ./.npmrc
          npm publish
